language: python
python:
  - '3.6'
dist: xenial
services:
  - xvfb
before_install:
  - sudo apt-get install --force-yes freeglut3-dev
install:
  - pip install .
before_script:
  - "ls -R"
script:
  - py.test
